### PR TITLE
Added Dinosaur_image

### PR DESCRIPTION
**Pull request by Davekibh**
Added Dinosaur_image @maxwofford

### CODE REVIEW

**Comment by sampoder** [comment]
hey @Davekibh! could you also add it to the README?

**Comment by Davekibh** [comment]
ok!

**Review by sampoder — APPROVED** [review]
now that's one Beautiful Dino!

**Comment by maxwofford** [comment]
I love it! It's so smooth

**Comment by Davekibh** [comment]
Thank you @maxwofford

**Pull request merged**
