### PR TITLE
Hi dino

### PR DESCRIPTION
**Pull request by souptik-samanta**

### CODE REVIEW

**Review by Shrey-Mehra — CHANGES_REQUESTED** [review]
Hey @souptik-samanta you need to add readme.md file too in this pull request

**Comment by souptik-samanta** [comment]
@Shrey-Mehra How do i make the readme ?
I want my description to be "Hello Dino!! :)
souptik_samanta_dino
"

**Comment by Shrey-Mehra** [comment]
Hey @souptik-samanta, you can follow this [guide](https://hack.af/make-dino) to make readme still stuck somewhere then feel free to DM me

**Review by NeonGamerBot-QK — APPROVED** [review]
fixed readme issue!

**Comment by souptik-samanta** [comment]
Thank you @NeonGamerBot-QK

**Review by Shrey-Mehra — APPROVED** [review]
Awesome work @NeonGamerBot-QK and you made an awesome dino @souptik-samanta i really like it

**Pull request merged**
