### PR TITLE
Added new cute orpheushacks dino

### PR DESCRIPTION
**Pull request by malteianlauterbach**

### CODE REVIEW

**Review by hkatzdev — CHANGES_REQUESTED** [review]
Wow, this is awesome! Can you please add it to the readme so everyone can see it too?

**Comment by malteianlauterbach** [comment]
sure, will do now.

**Comment by hkatzdev** [comment]
Bump :)

**Comment by hkatzdev** [comment]
This is a Special Exception for Orpheus Hacks - please note potential future contributors that you must add the dinosaur to the readme yourself in order to complete the draw dino workshop :)

**Review by hkatzdev — APPROVED** [review]
Tested on branch so approving my own commit

**Pull request merged**
