### PR TITLE
Oh hello there! 🎩

### PR DESCRIPTION
**Pull request by FrenzyExists**
"FrenzyExists_ClassyDino"

image

Just passing by around the folk. Here: a classy dino passes by in tuxedo and aristocratic words expresses with pride

### CODE REVIEW

**Comment by FrenzyExists** [comment]
mmm, that's strange

**Review by sampoder — CHANGES_REQUESTED** [review]
that's classy! could you add it to the README?

**Comment by FrenzyExists** [comment]
Sorry for the late reply, I'll add it to the README, thanks!

**Comment by FrenzyExists** [comment]
Hmm, strange, I indeed added the dino to the README and followed the same formatting, is there anything I might missing?

**Review by sampoder — APPROVED** [review]
it's there now 🎩

**Comment by FrenzyExists** [comment]
:+1:

**Pull request merged**
