### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ni5arga**
Added my dino!

### CODE REVIEW

**Review by sampoder — CHANGES_REQUESTED** [review]
Crazy dino! Can you add it to the README?

**Comment by ni5arga** [comment]
which readme

**Comment by sampoder** [comment]
The repo's README.

**Comment by ni5arga** [comment]
sure, wait a sec.

**Comment by ni5arga** [comment]
I've accidentally opened a separate readme for that

**Comment by ni5arga** [comment]
https://github.com/hackclub/dinosaurs/pull/734

**Comment by ni5arga** [comment]
I've accidentally opened a separate PR for that

**Pull request merged**
