### PR TITLE
Orpheus Overhaul

### PR DESCRIPTION
**Pull request by jacobhaap**
Improve accessibility of repository, addition of website currently located at orpheus-dinos.netlify.com

### CODE REVIEW

**Comment by maxwofford** [comment]
Love the website, but removing the README.md conflicts with the steps on https://hack.af/draw-dino.

Could the website build from the markdown?

**Comment by jacobhaap** [comment]
Would I be able to update the steps on draw-dino? I could make a fork of the repository and update to match the new stuff.

**Comment by maxwofford** [comment]
I'd like to keep the dino-draw workshop as is for now. I love the idea of a website for the dinosaurs though. Interested in building a site that builds from this repo's markdown in a similar way to how https://workshops.hackclub.com's content comes from https://github.com/hackclub/hackclub?

**Comment by jacobhaap** [comment]
I forked the workshops repository to learn more about the site build from markdown. I'm closing the PR for now and will open a new one once redeveloped.

**Pull request closed without merging**
