### PR TITLE
Add tired-dino and aaaaa-dino

### PR DESCRIPTION
**Pull request by eilla1**
This PR adds some more dinos!

### CODE REVIEW

**Comment by eilla1** [comment]
btw do you need any help reviewing PRs on this repo? If so, I'd be down to help

**Comment by maxwofford** [comment]
@eilla1, that'd be dope, thanks! i think you have merge permission but if not lmk

also, these are my 2 new favorite dinos, they're so cute!

**Comment by eilla1** [comment]
Screen Shot 2021-09-27 at 9 36 25 AM
awesome thanks @maxwofford! I don't think I have permission to merge

**Comment by maxwofford** [comment]
# yer an admin, harry

Screen Shot 2021-09-27 at 15 13 21

**Pull request merged**
