### PR TITLE
Recapxd gojo dino   ik is bad dont hate me pls  

### PR DESCRIPTION
**Pull request by RECAPXD**

### CODE REVIEW

**Review by Shrey-Mehra — CHANGES_REQUESTED** [review]
Hey @RECAPXD , can you please re-upload the image of Dino.

image

**Comment by RECAPXD** [comment]
RECAPXD_gojo_dino___ik_is_bad_dont_hate_me_pls__

**Comment by Shrey-Mehra** [comment]
You have to re-upload the image by removing previous one

**Review by ni5arga — CHANGES_REQUESTED** [review]
Can't merge this, the image isn't rendering on my side - please reupload the image.

**Comment by Shrey-Mehra** [comment]
Hey @RECAPXD , I'm closing this pull request due to no response.

Thanks

**Pull request closed without merging**
