### PR TITLE
Additional msw dinos (part 2)

### PR DESCRIPTION
**Pull request by maxwofford**

### CODE REVIEW

**Review by Shrey-Mehra — COMMENTED** [review]
Hey @maxwofford , Your dino collection is awesome.
I have a query have you added the image too of `dino_in_a_teapot.png`

**Comment by Shrey-Mehra** [comment]
sure 😀

**Comment by maxwofford** [comment]
Ah, looks like that was already added in https://github.com/hackclub/dinosaurs/pull/885

**Comment by Shrey-Mehra** [comment]
Sure lol

**Pull request merged**
