### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by necrosis2010**

### CODE REVIEW

**Comment by necrosis2010** [comment]
Updated to Readme

**Comment by maxwofford** [comment]
Closing this because the file "necrosis2010-chillnibs.png" is missing – feel free to add that image back and we can reopen it

**Comment by necrosis2010** [comment]
I'm new to Git and its applications that's why I'm asking this....was I not supposed to delete the file from my computer?

**Comment by maxwofford** [comment]
@necrosis2010 no problem! I’m the person that made https://hack.af/draw-dinos & I’m happy to walk you through it.

I think the file was deleted before you uploaded it to GitHub. Go to https://github.com/hackclub/dinosaurs/tree/necrosis2010-chillnibs and click “upload files”, the upload your Dino drawing.

**Comment by necrosis2010** [comment]
Thanks a lot! I've done as per your instructions.

**Pull request closed without merging**
