### PR TITLE
My first contribution in Hack-Club

### PR DESCRIPTION
**Pull request by mohdsultan18**
This is my first contribution in Hack Club

### CODE REVIEW

**Review by Shrey-Mehra — CHANGES_REQUESTED** [review]
Hey @mohdsultan18 that's amazing that it's your first commit for Hack Club to complete it please add` .README.md` file too

**Comment by mohdsultan18** [comment]
Hi @Shrey-Mehra Can you pls guide to how to do that step as I am having difficulty doing it :)

**Comment by Shrey-Mehra** [comment]
Yeah sure buddy,

**Comment by mohdsultan18** [comment]
Thank you

**Comment by Shrey-Mehra** [comment]
Go through this [Guide](https://hack.af/draw-dino). If you face any issues feel free to comment here 😀

**Comment by mohdsultan18** [comment]
There is no info about readme file there

**Comment by mohdsultan18** [comment]
If you can tell me in a simple way how to add readme file, it would be really helpful. 
I know how to add readme but here I just added png file that why having confusion

**Comment by Shrey-Mehra** [comment]
Ok just give a minute

**Comment by mohdsultan18** [comment]
Yeah, sure

**Comment by mohdsultan18** [comment]
Yeah, readme file is their

**Comment by mohdsultan18** [comment]
What to do with it now??

**Comment by Shrey-Mehra** [comment]
and write name whcih you use to save the dino on your system

**Comment by Shrey-Mehra** [comment]
and write name whcih you use to save the dino on your system

**Comment by mohdsultan18** [comment]
Done from my end, can you please review it and I think we are ready for merge.

**Comment by Shrey-Mehra** [comment]
Add like this

"Shrey_Mehra_dino"

**Comment by Shrey-Mehra** [comment]
Sorry for closing

**Comment by mohdsultan18** [comment]
Do I have to do anything else? I think I did what you said.

**Review by Shrey-Mehra — APPROVED** [review]
Amazing that's what you have do . You really sharp minded man. So I'm merging this pull request because also issue is resolved

**Comment by Shrey-Mehra** [comment]
One this more anytime need any help DM on Slack my username is `Shrey Mehra`

**Comment by mohdsultan18** [comment]
@Shrey-Mehra Thank you too, really appreciate your work and for sure I am gonna text on you slack. Stay blessed

**Pull request merged**
