### PR TITLE
Add jlevy_dev_dino to README

### PR DESCRIPTION
**Pull request by jlevy-dev**

### CODE REVIEW

**Review by hkatzdev — CHANGES_REQUESTED** [review]
Hey, thank you for contributing @jlevy-dev! I think you forgot to upload your image though :). Once you upload your image I can approve this!

**Comment by jlevy-dev** [comment]
jlevy_dev_dino

**Comment by jlevy-dev** [comment]
I think I did it?

**Review by sampoder — APPROVED** [review]
welcome to the team! 🦖

**Pull request merged**
