### PR TITLE
Change Orpheus pronouns

### PR DESCRIPTION
**Pull request by avascherocman**
From "it" to "she" in "the dinosaur who can never look back". Feel free to close if it doesn't match with the original intent of the writing

### CODE REVIEW

**Comment by maxwofford** [comment]
Hmmmm... not sure what to do here b/c it's a quote. Agree with the intent of the change, but I think directly editing the quote like this feels funny.

Just googled around for modifying quotes– seems like we can use [square brackets to annotate a change](https://writingcommons.org/open-text/research-methods-methodologies/integrate-evidence/incorporate-evidence/453-inserting-or-altering-words-in-a-direct-quotation). Thoughts on using that?

**Comment by avascherocman** [comment]
Was the quote originally about Orpheus?

**Comment by lachlanjc** [comment]
Yeah, I think the square brackets make sense here. That’s the standard for essays, etc where you need to change subjects/pronouns.

**Comment by avascherocman** [comment]
Okay, I agree. Making a new PR and closing this one.

**Comment by maxwofford** [comment]
@avascherocman feel free to leave open & add new commits to this PR

**Comment by avascherocman** [comment]
Should I merge? Added the brackets

**Pull request merged**
