### PR TITLE
Add new dino: the happy dino

### PR DESCRIPTION
**Pull request by wesleybertipaglia**

### CODE REVIEW

**Review by SwiftyProgrammer690 — APPROVED** [review]
Looks good to me! I think this should be added.

**Review by Shrey-Mehra — APPROVED** [review]
yeah, it's looking awesome. so I'm merging it

**Comment by wesleybertipaglia** [comment]
> yeah, it's looking awesome. so I'm merging it

Thanks 😀

**Comment by wesleybertipaglia** [comment]
> Looks good to me! I think this should be added.

Thanks 😀

**Pull request merged**
