### PR TITLE
Genr234 dinoesse

### PR DESCRIPTION
**Pull request by genr234**

### CODE REVIEW

**Comment by mattsoh** [comment]
Very nice! @genr234

**Comment by mattsoh** [comment]
Uhh hang on...please change your README.md file so that the name of your png file matches the actual filename. Thanks!

`` needs to be changed to ``. Please also check that the photo actually shows on the README.md file

**Comment by mattsoh** [comment]
@genr234

**Comment by mattsoh** [comment]
Go back to your branch, edit the README.md of your branch so that the filename is correct, then check if the image shows there and then open another pull request, thanks!

(Yeah sorry I accidentally merged it)

**Review by mattsoh — COMMENTED** [review]
Line 3663 needs to be changed, thanks!

**Comment by genr234** [comment]
Sorry! Opening another one 😅

**Comment by genr234** [comment]
Just opened #1137

**Pull request merged**
