### PR TITLE
Add dino w hat

### PR DESCRIPTION
**Pull request by Brian3647**

### CODE REVIEW

**Comment by Brian3647** [comment]
Also, could you add me to slack? using https://hackclub.com/slack/ gives "500 internal server error" in console

Email: victoris3647@gmail.com
Name: Víctor Ibáñez (Aka Brian3647)

If needed, I can also add the reason to this comment

**Review by eilla1 — APPROVED** [review]
🧢

**Comment by eilla1** [comment]
Could you provide more details about the error on hackclub.com/slack? It should be working

**Comment by Brian3647** [comment]
> Could you provide more details about the error on hackclub.com/slack? It should be working

There's no much more information.
Error in browser

I opened [an issue](https://github.com/hackclub/v3/issues/235) for this a while ago (the error message showed using curl):

Error with curl

**Comment by eilla1** [comment]
That's weird; it seems to be working fine for me 🤔 anyways, I invited your email to the Slack! Let me know if you received it!

**Comment by Brian3647** [comment]
thanks! already joined

**Pull request merged**
