### PR TITLE
Add M4ntis67_dinosus_bro.png

### PR DESCRIPTION
**Pull request by M4ntis67**

### CODE REVIEW

**Review by sampoder — CHANGES_REQUESTED** [review]
heyyyy this PR looks a bit sus, can you add your dino to the README?

**Review by sampoder — APPROVED** [review]

**Comment by FrenzyExists** [comment]
so um, sorry if I ask over here, I made a dino, buuut never done a PR request before so, I'm kinda lost on such, do i have to git clone it, add my pic and push it or something? Again i know this is prob something basic, so i apologize my stupidity

**Comment by kdgyimah** [comment]
@FrenzyExists You can follow the interactive guide on the Draw Dino page here and you should be fine: https://draw-dino.hackclub.com/


For additional context:

username - Is your github username
dinoName - Is the name you saved the dino image


- Create a branch with the name: "username_dinoName"
create_branch



- Click “Add file” and add your dino image
- Below “Commit changes”, type this into the first text box: "Add username_dinoName.png"
- Then click COMMIT CHANGES
- Do not click the green button that says "Create pull request" just yet.
- Scroll through the list of files & find “README.md”.
- Then you edit the file, by clicking the edit icon.
- Scroll to the bottom and Add the Caption and a ref for the dino image to the bottom of the file:
```
"username_dinoName"

![](username_dinoName.png)
```
- Below “Commit changes”, type "Add username_dinoName to README" in the first text box
- Then click COMMIT CHANGES
- Go back to https://github.com/hackclub/dinosaurs and click Compare & pull request.
- Then click Create pull request

**Comment by FrenzyExists** [comment]
Got it! Gonna do that, thanks :+1:

**Comment by FrenzyExists** [comment]
Hi again, so, I made my request, however, it got rejected for some reason, its currently at the pull requests, is there something I'm missing on my commit? It has the name format just like the instructions, and it also has the picture on the request as mentioned too. I apologize for the trouble

**Pull request merged**
