### PR TITLE
Dino

### PR DESCRIPTION
**Pull request by Rohit-86**
Here i'm completed the dino diagram
can anybody gide me what to do next

### CODE REVIEW

**Comment by kunaljaykam** [comment]
Good job @Rohit-86. Now you have to update the `README.md` file with you dino name. Check out the screenshot I have attached to get it right. 
Screenshot from 2023-12-27 00-48-52

**Review by Rohit-86 — COMMENTED** [review]
Hello!!
This is My First Open Source Expreience!!

**Comment by Shrey-Mehra** [comment]
> Hello!! This is My First Open Source Expreience!!

that's sound awesome

**Review by Shrey-Mehra — CHANGES_REQUESTED** [review]
Kindly Add README.md file to it, you can take help of link which is shared by @ajs256 

If there is any issue in understanding you contact me on [slack](https://hackclub.slack.com/team/U04DWQ6BWJF)
OR
you can mail me on [shrey.codethetech@gmail.com](mailto:shrey.codethetech@gmail.com)

**Review by kunaljaykam — APPROVED** [review]
Thanks @Rohit-86 . Looks good to me!

**Review by Shrey-Mehra — APPROVED** [review]
Looks awesome 😎

**Pull request merged**
