### PR TITLE
Orpheus for Orpheus-Sat

### PR DESCRIPTION
**Pull request by aaravporwal**
Orpheus goes to moon!! this doodle is for orpheus-satellite

This is a transparent image! so you can add it in that folder too

### CODE REVIEW

**Review by hkatzdev — CHANGES_REQUESTED** [review]
Looks awesome! I think you forgot to add your image to the readme though.

**Comment by aaravporwal** [comment]
Thanks I'll ad it in the readme and send another one 🚀

**Comment by aaravporwal** [comment]
Hey! can I add a note in the readme so that people don't forget to link their dinos in Readme?

**Comment by maxwofford** [comment]
Please!

Max Wofford
max@maxwofford.com
Engineering & Operations @ Hack Club ( https://hackclub.com )

**Pull request merged**
