### PR TITLE
Add dalio48_dinoyo.png

### PR DESCRIPTION
**Pull request by dalio48**

### CODE REVIEW

**Comment by Arpan-206** [comment]
Hey, you also need to add the file to the `README.md` file. Can you please make the change before we can approve? If you need any help, feel free to ask on Slack.

**Review by ni5arga — CHANGES_REQUESTED** [review]
Please add the file in README.md

**Review by Shrey-Mehra — CHANGES_REQUESTED** [review]
Hey @dalio48 ,kindly add the file to the README.md file.

**Comment by Arpan-206** [comment]
Closing due to no response.

**Pull request closed without merging**
