### PR TITLE
updated readme.md

### PR DESCRIPTION
**Pull request by 889-dj**

### CODE REVIEW

**Comment by eilla1** [comment]
To edit the README, you'll want to go here https://github.com/hackclub/dinosaurs/blob/889-dj-patch-2/README.md and click on the pencil button in the top right!
Screen Shot 2022-01-07 at 9 01 51 AM

**Review by eilla1 — APPROVED** [review]
Yay amazing, thank you @889-dj and welcome to the club! 🦕

**Comment by 889-dj** [comment]
> To edit the README, you'll want to go here https://github.com/hackclub/dinosaurs/blob/889-dj-patch-2/README.md and click on the pencil button in the top right! Screen Shot 2022-01-07 at 9 01 51 AM

thanks for helping out :)

**Comment by 889-dj** [comment]
> Yay amazing, thank you @889-dj and welcome to the club! 🦕

thanks 🙂

**Pull request merged**
