### PR TITLE
ROOAARRR!

### PR DESCRIPTION
**Pull request by Huseyin-Cinar**

### CODE REVIEW

**Comment by Huseyin-Cinar** [comment]
**When accepting my dino ^_^ WOOAARRR**

**Review by sampoder — CHANGES_REQUESTED** [review]
I think you mean ROOAARRR! Can you add this dino to the README?

**Review by jzaleta — CHANGES_REQUESTED** [review]
Add the dino link to the main README.md file instead 🦕

**Comment by jzaleta** [comment]
I added your dino to the readme correctly so that you no longer had any problems with the file, congrats for drawing it.
MERGED!

**Pull request merged**
