### PR TITLE
euphorichubbbb_dino

### PR DESCRIPTION
**Pull request by euphorichubbbb**

### CODE REVIEW

**Comment by Shrey-Mehra** [comment]
Hey @euphorichubbbb , I'm Closing this PR due to no response

**Comment by euphorichubbbb** [comment]
I am not getting how  to do it can u give me some accurate steps

**Comment by Shrey-Mehra** [comment]
Hey @euphorichubbbb, here is the link - [https://hack.af/draw-dino](https://hack.af/draw-dino). This will help you.


if you have any queries just ping me @Shrey-Mehra  or on Slack [Shrey Mehra](https://hackclub.slack.com/archives/D0568316JCT)

Thanks 😄

**Comment by Shrey-Mehra** [comment]
Hey @euphorichubbbb 👋, did you need any help with Readme file??

**Comment by Shrey-Mehra** [comment]
Hey @euphorichubbbb , I'm Closing this PR due to no response

**Pull request closed without merging**
