### PR TITLE
Sahitid binary dino

### PR DESCRIPTION
**Pull request by sahitid**

### CODE REVIEW

**Review by sampoder — APPROVED** [review]
dino! dino! this is sick! could you change the file name to `sahitid_binary_dino.png`?

**Review by sampoder — CHANGES_REQUESTED** [review]
dino! dino! this is sick! could you change the file name to sahitid_binary_dino.png?

**Comment by sahitid** [comment]
correct me if i'm wrong, but isn't the file name already "sahitid_binary_dino.png"?

**Comment by sampoder** [comment]
it's currently sahitid_binary_dino.png.png

**Pull request closed without merging**
