### PR TITLE
Added yazdanhaider's dino contri

### PR DESCRIPTION
**Pull request by yazdanhaider**

### CODE REVIEW

**Review by DillonB07 — APPROVED** [review]
nice dino!

**Review by DillonB07 — CHANGES_REQUESTED** [review]
please add this to the bottom of the readme file not the top

**Review by NeonGamerBot-QK — CHANGES_REQUESTED** [review]
Conflicts

**Comment by DillonB07** [comment]
Hi @crabby605 this isn't ready to be merged yet because you're adding your dinosaur at the top of the file. Please modify the README.md to add it at the bottom by moving the lines you've added

**Comment by Shrey-Mehra** [comment]
Hey @DillonB07 
Within 1-2 I'll resolve conflict because it can be resolved from our end only

**Comment by crabby605** [comment]
> Hi @crabby605 this isn't ready to be merged yet because you're adding your dinosaur at the top of the file. Please modify the README.md to add it at the bottom by moving the lines you've added

Nah the closure of PR was accidental

**Review by Shrey-Mehra — APPROVED** [review]
I'm merging it as I settled everything

**Pull request merged**
