### PR TITLE
Anu oluwatomiwa dino

### PR DESCRIPTION
**Pull request by AnuOluwatomiwa**

### CODE REVIEW

**Review by Shrey-Mehra — CHANGES_REQUESTED** [review]
Hey @AnuOluwatomiwa , your image is not uploaded correctly can you please re-upload it

**Comment by Shrey-Mehra** [comment]
See when you're uploading the image wait for image to upload after all loading are successfully done click on commit

**Review by ni5arga — CHANGES_REQUESTED** [review]
Please upload the image as a `.png` file.

**Review by Shrey-Mehra — APPROVED** [review]
everything looks fine

**Pull request closed without merging**
