### PR TITLE
taylorylee_dino_thisisfine.png

### PR DESCRIPTION
**Pull request by taylorylee**

### CODE REVIEW

**Comment by taylorylee** [comment]
Haha thanks! I am having trouble committing it to the master branch because it says it's blocked for security reasons. @hkatzdev

**Comment by taylorylee** [comment]
taylorylee_dino_thisisfine

**Comment by lachlanjc** [comment]
@taylorylee No worries! You can’t directly commit to the main branch of the project; you’ll want to commit to your branch, which will then be added to this PR & our team will merge it into the project. To do this, under the PR title at the top of the page, click your branch name in blue, then click the README file, then edit there. Would love to have your dino!!

**Comment by hkatzdev** [comment]
Bump :)

**Comment by hkatzdev** [comment]
Closing due to inactivity - feel free to reopen though!

**Pull request closed without merging**
