### PR TITLE
feat: dino

### PR DESCRIPTION
**Pull request by NeonGamerBot-QK**

### CODE REVIEW

**Review by defihook — COMMENTED** [review]
"PRATIKNALAWADE-DINO-JOEY-HOW-U-DOING_.png"

**Comment by NeonGamerBot-QK** [comment]
> "PRATIKNALAWADE-DINO-JOEY-HOW-U-DOING_.png"

? is that what you want me to make the new filename?

**Comment by NeonGamerBot-QK** [comment]
? status on merge?

**Review by DillonB07 — CHANGES_REQUESTED** [review]
Please only add your own dino - don't change any other entries

**Comment by NeonGamerBot-QK** [comment]
> Please only add your own dino - don't change any other entries

i was resolving conflicts in the README.md

**Comment by NeonGamerBot-QK** [comment]
@DillonB07 fixed/

**Review by DillonB07 — APPROVED** [review]
cool!

**Pull request merged**
