### PR TITLE
Add Dino in a city

### PR DESCRIPTION
**Pull request by Vishal1297**
- [x] Add new dino
- [x] Updated README.md

### CODE REVIEW

**Review by markrosenbaum — APPROVED** [review]
+1

**Review by gambhirsharma — APPROVED** [review]

**Review by akhil888binoy — APPROVED** [review]

**Review by VulcanWM — APPROVED** [review]
great job!

**Review by VulcanWM — APPROVED** [review]
nice work!

**Comment by Vishal1297** [comment]
Can anyone of you approve?

**Review by akhil888binoy — APPROVED** [review]

**Pull request merged**
