### PR TITLE
Add Kipp_ie_dino.png

### PR DESCRIPTION
**Pull request by Kipp-ie**

### CODE REVIEW

**Review by ajs256 — CHANGES_REQUESTED** [review]
Hey @Kipp-ie, can you please add the dino to the README file in the same pull request? It helps keep the repository's history clean. Thanks!

**Review by DillonB07 — APPROVED** [review]
this is an awesome dino!

**Review by DillonB07 — CHANGES_REQUESTED** [review]
Oops, as alex mentioned, please add to README in the same PR!

**Comment by Shrey-Mehra** [comment]
Hey @Kipp-ie , i'm closing this pull request as there is no update from 3 weeks

Feel free to DM me on Slack

**Pull request closed without merging**
