### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by UnderCurve**

### CODE REVIEW

**Comment by arnavravinder** [comment]
Hi, please add it to the README.md as well .

**Review by Shrey-Mehra — CHANGES_REQUESTED** [review]
Hey @UnderCurve ,
As I look you have created two different repo for `readme.md` and  `your dino`
I request you to please close that one and made the `Readme.md` file here 

If you face any issues feel free to DM me on Slack or reply here

Regards 
Shrey Mehra

**Comment by UnderCurve** [comment]
I have done as you have asked

**Review by Shrey-Mehra — APPROVED** [review]
Awesome man that's quite fast.everthing looks good to me so merging this pull request 😄

**Pull request merged**
