### PR TITLE
Add images from prophet-orpheus-role-play

### PR DESCRIPTION
**Pull request by MaxWofford**
random fact of the day:

### CODE REVIEW

**Comment by MaxWofford** [comment]
@zachlatta *ping

**Comment by zachlatta** [comment]
Can you rebase `master` into this? Then I'll merge :-).

**Comment by jonleung** [comment]
What have I just stumbled upon?! Gold?! Pure gold?!

**Comment by zachlatta** [comment]
_dino dance party_

**Comment by jonleung** [comment]
https://www.youtube.com/watch?v=w31bAfGdKB4

**Pull request closed without merging**
